language: objective-c
before_install: cd Example && pod install && cd -
script:
- xctool test -workspace Example/RequestInMemory.xcworkspace -scheme RequestInMemory -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
